### ISSUE TITLE
465307D7 / 465307D1 - Tenchu Z, Tenchu Senran

### ISSUE THREAD

**Issue by xDayDreams** [xenia-project/game-compatibility#2226] opened 2024-09-20 03:52 UTC
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch. (not MLBS/AlexVS/Canary/pull requests, etc)
- [X] This issue isn't for help (tech support) with Xenia, or a game.
- [X] I've checked if this game doesn't already have a compatibility report.

### Xenia version

https://github.com/xenia-project/xenia/commit/0ad1e3d5855cdf8e3c4ee20f7d3ba5ebc20c2edd/

### Issues

# **Tenchu Z / Tenchu Senran Issues**

(These are basically the same game with Senran being the Japanese version)

I've encountered some heavy graphical issues with *Tenchu Z* and *Tenchu Senran* when using Xenia Canary (latest patches). The main problem is related to skipping cutscenes:

- **Cutscene Skipping Bug**: Skipping cutscenes too early or at specific points often causes heavy graphical issues, forcing me to restart the mission. This issue occurs even with the internal display resolution set to default.
  
- **Resolution Scaling Problem**: Increasing the draw resolution scale worsens the problem, causing the game to have these issues more frequently—even if I don’t skip cutscenes.

These issues are present in both the English version (*Tenchu Z*) and the Japanese version (*Tenchu Senran*).

In addition, while not a major issue, I'd like to point out some performance concerns with Vulkan:

- **Vulkan Bugs**: When using Vulkan, some objects become invisible, and several bugs start to appear. I understand Vulkan is not yet fully stable, but it's worth noting this issue.

**Note**: I'm using Xenia Canary with the latest patches.

I've attached some screenshots below for reference:

1. The first two screenshots show what happens when skipping cutscenes.
2. The third screenshot illustrates objects (such as roofs) becoming invisible in Vulkan, an issue that also occurs during missions.
3. The last two screenshots capture bugs that appear after completing a mission while using Vulkan.

Please let me know if you need any additional information.

### Log

[xenia log Tenchu Z.zip](https://github.com/user-attachments/files/17069535/xenia.log.Tenchu.Z.zip)
[xenia log Tenchu Senran.zip](https://github.com/user-attachments/files/17069411/xenia.log.Tenchu.Senran.zip)
[xenia log Tenchu Z Vulkan.zip](https://github.com/user-attachments/files/17069488/xenia.log.Tenchu.Z.Vulkan.zip)
[xenia log Tenchu Senran Vulkan.zip](https://github.com/user-attachments/files/17069508/xenia.log.Tenchu.Senran.Vulkan.zip)

### Screenshots

![Tenchu bug 1](https://github.com/user-attachments/assets/6dffba19-b234-431f-a13d-69ff2ea16c2d)
![Tenchu bug 2](https://github.com/user-attachments/assets/bae1e932-c21d-44c8-8f36-736749dddae3)
![Tenchu bug 3](https://github.com/user-attachments/assets/d814636b-45c1-492c-9515-ded1020a484e)
![Tenchu Bug 4](https://github.com/user-attachments/assets/4963545c-a640-45ec-a42b-75580329877e)
![Tenchu bug 5](https://github.com/user-attachments/assets/cfcc008a-7378-4479-a566-ddd117725ab2)

### Labels

state-gameplay, gpu-drawing-corrupt

**Comment by Margen67** [comment] 2024-09-20 05:35
Duplicate of #592

**Closed by Margen67** 2024-09-20 05:35 UTC
Labels: issue-duplicate
