### ISSUE TITLE
Ace Combat 6: Fires of Liberation. No Sound In Cutscenes.

### ISSUE THREAD

**Issue by RUSE35** [xenia-project/game-compatibility#1444] opened 2019-09-27 19:26 UTC
Tested on https://github.com/xenia-project/xenia/commit/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# Issues:
Game will reach gameplay but sound in menus constantly loops and cutscenes in-engine have no sound.

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/3664267/xenia.zip)

# Screenshot(s):
It's sound related. Other issues pertaining to gameplay have already been documented.

# Labels:
(recommended labels)
apu-silent
apu-garbage

**Comment by Margen67** [comment] 2019-09-27 21:08
Inferior duplicate of #419.

**Closed by Margen67** 2019-09-27 21:08 UTC
Labels: issue-duplicate, issue-invalid

**Comment by Margen67** [comment] 2019-10-24 02:03
Duplicate of #419.
