### ISSUE TITLE
58411430 - Slender - The Arrival

### ISSUE THREAD

**Issue by OfficerObese** [xenia-project/game-compatibility#505] opened 2016-07-04 06:35 UTC
[Marketplace](https://marketplace.xbox.com/en-AU/Product/Slender-The-Arrival/66acd000-77fe-1000-9115-d80258411430)

Tested on (https://github.com/benvanik/xenia/commit/3d1d4dea47dd95117befe436ed292ad79ca5ee13
# Issues:

(state-crash)
# Log:

[Log file](https://gist.github.com/PcDivision/8652deac1a2bb8dfff1175dfde0dfc19)
# Screenshot(s):

![](http://puu.sh/pPDMQ/49f33c7fb4.jpg)
# Labels:

(state-crash)

**Comment by bdeimos** [comment] 2018-06-30 17:01
Tested on (https://github.com/xenia-project/xenia/commit/f89b4626a37dd4d1e5a817909252d3d4dd054299)

(state-crash-guest)

[xenia.zip](https://github.com/xenia-project/game-compatibility/files/2152024/xenia.zip)

**Comment by win98and95** [comment] 2019-02-12 09:53
Duplicate of https://github.com/xenia-project/game-compatibility/issues/197

**Closed** 2019-07-07 15:49 UTC
Labels: state-crash-OBSOLETE
