### ISSUE TITLE
315A07D2 - WWE 2K16 

### ISSUE THREAD

**Issue by FarshadGrayson** [xenia-project/game-compatibility#1499] opened 2020-03-01 23:05 UTC
[Marketplace](https://marketplace.xbox.com/en-US/Product/WWE-2K16/66acd000-77fe-1000-9115-d802315a07d2)

Tested on https://github.com/xenia-project/xenia/commit/8d5d70c77f6aa4a4271ab0d8d1a00b9c9aaca217

# Issues:
Shows the guest has crashed message and won't boot the game up

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/4272662/xenia.zip)

# Screenshot(s):
![Crash1](https://user-images.githubusercontent.com/23382820/75635765-da103380-5c2d-11ea-9466-721c88531b66.JPG)
![Crash2](https://user-images.githubusercontent.com/23382820/75635766-dbd9f700-5c2d-11ea-97ef-39226f37d703.JPG)

# Labels:
[state-crash-guest](https://github.com/xenia-project/game-compatibility/labels/state-crash-guest)

**Comment by Margen67** [comment] 2020-03-02 18:09
Duplicate of #257.

**Closed by Margen67** 2020-03-02 18:09 UTC
Labels: issue-duplicate
