### ISSUE TITLE
4156083D - Guitar Hero Van Halen

### ISSUE THREAD

**Issue by Moksssx** [xenia-project/game-compatibility#2224] opened 2024-09-04 01:22 UTC
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch. (not MLBS/AlexVS/Canary/pull requests, etc)
- [X] This issue isn't for help (tech support) with Xenia, or a game.
- [X] I've checked if this game doesn't already have a compatibility report.

### Xenia version

https://github.com/xenia-project/xenia/commit/.../

### Issues

I don't have any problem with the performance but i have a problem in audio delay even i set the max apu frames to 64 still getting some super delay on audio

### Log

[xenia.zip](https://github.com/user-attachments/files/16859545/xenia.zip)

### Screenshots

![image](https://github.com/user-attachments/assets/1ccff7bf-63d9-4322-8180-02a614d5549c)
![image](https://github.com/user-attachments/assets/62b9d8bf-5c94-48b7-9775-8ac2fa002453)

### Labels

state-gameplay, apu-frames

**Comment by Margen67** [comment] 2024-09-06 20:22
Duplicate of #1207

**Closed by Margen67** 2024-09-06 20:22 UTC
