### ISSUE TITLE
555308B7 - Watch Dogs

### ISSUE THREAD

**Issue by Bryan1998** [xenia-project/game-compatibility#1144] opened 2019-02-02 02:18 UTC
[Marketplace]https://marketplace.xbox.com/en-US/Product/Watch-Dogs/66acd000-77fe-1000-9115-d802555308b7

Tested on https://github.com/xenia-project/xenia/commit/a05a7d8fc0d1beebd0c03385b740a8d490f4f6b9

# Issues:
Crashes when loading "game.xex"
Black screen when loading "default.xex"

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/2823942/xenia.zip)

# Screenshot:
![image](https://user-images.githubusercontent.com/24740306/52158481-9ffce880-264d-11e9-842e-009a692f1046.png)

# Labels:
crash-state-guest

**Comment by ZolaKluke** [comment] 2019-02-02 02:32
Please close this issue as this is a duplicate of: https://github.com/xenia-project/game-compatibility/issues/940

**Comment by Bryan1998** [comment] 2019-02-02 02:57
It's not a duplicate, I made it a step further, and that issue has been around since May last year.

**Comment by ZolaKluke** [comment] 2019-02-02 03:01
You still don't open a new issue, you comment on an existing one with your new findings take this one as an example: https://github.com/xenia-project/game-compatibility/issues/988
It's the same game compatibility listing, it's just had new info added to it since updates of Xenia have been released

**Closed** 2019-02-02 03:10 UTC

**Comment by Bryan1998** [comment] 2019-02-02 03:13
Looks like this game will never be compatible, just like many others...

**Comment by ZolaKluke** [comment] 2019-02-02 03:15
It will be compatible, Xenia is still early in development unlike most emulators out there come back in a few months and maybe if some cpu sided work is done then the game might become playable
