### ISSUE TITLE
4E4D080B - Magna Carta 2

### ISSUE THREAD

**Issue by yukinomose** [xenia-project/game-compatibility#1613] opened 2020-08-15 18:56 UTC
https://marketplace.xbox.com/en-us/Product/Magnacarta2/66acd000-77fe-1000-9115-d8024e4d080b

Tested on https://github.com/xenia-project/xenia/commit/1708a24881fa2f7c4009162acc49252af95e0383

# Issues:
the game crash to Abazet Port - message the guest has crashed, Xenia has now paused itself. A crash dump has been written into the log"

# Log:
[xenia log.zip](https://github.com/xenia-project/game-compatibility/files/5079284/xenia.log.zip)

# Screenshot(s):
![crash](https://user-images.githubusercontent.com/69730119/90319591-c9cce600-df39-11ea-9b50-d4bcf795f848.png)

# Labels:
(recommended labels)

**Comment by Etokapa** [comment] 2020-08-15 19:00
Dupe of #721

**Comment by yukinomose** [comment] 2020-08-15 19:40
> Dupe of #721

yes but there is a way to fix the Abazet bug ?

**Comment by yukinomose** [comment] 2020-08-24 12:20
bump. There are tips to fix the issue ?

**Comment by Gliniak** [comment] 2020-08-24 17:54
Duplicate of #721 

Do not create issues for entry that already exists.

**Closed by Gliniak** 2020-08-24 17:54 UTC
