### ISSUE TITLE
4E4D07DC - Beautiful Katamari

### ISSUE THREAD

**Issue by medama** [xenia-project/game-compatibility#1648] opened 2020-11-16 15:02 UTC
[Marketplace](http://marketplace.xbox.com/en-US/Product/Beautiful-Katamari/66acd000-77fe-1000-9115-d8024e4d07dc)
Tested on https://github.com/xenia-project/xenia/commit/87a3c5fac2d3ccf9e7bdb7076038cd9e889a31f6

# Issues:
Audio Issues: The audio does not play correctly in some scenes. 
ie: [Youtube Link](https://youtu.be/3Afx67_YZvw)  (0:05~)
Graphic issues: Some things are not displayed correctly.
ie: [Youtube Link](https://youtu.be/3Afx67_YZvw?t=16)
# Screenshot(s):
![コメント 2020-11-03 164934](https://user-images.githubusercontent.com/39562468/99267468-52c02a00-2867-11eb-8bda-46d6e0155c52.jpg)

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/5546905/xenia.zip)

# Labels:
state-gameplay

**Comment by Gliniak** [comment] 2020-11-16 15:04
Duplicate of #297

**Closed by Gliniak** 2020-11-16 15:04 UTC

**Comment by medama** [comment] 2020-11-16 15:07
I don't think the problem is duplicated because the startup itself is done.
