### ISSUE TITLE
4E4D07D1 - Ace Combat 6

### ISSUE THREAD

**Issue by Parovozik** [xenia-project/game-compatibility#980] opened 2018-06-23 02:47 UTC
[Marketplace](https://marketplace.xbox.com/en-US/Product/ACE-COMBAT-6/66acd000-77fe-1000-9115-d8024e4d07d1)

Tested on (https://github.com/xenia-project/xenia/commit/2314f25fb7252bb9054fd7c863e1a57bee90282d)

# Issues:
Gameplay, but some troubles on graphics part

# Log:
[Ace Combat 6.log](https://github.com/xenia-project/game-compatibility/files/2129572/Ace.Combat.6.log)

# Screenshot(s):
![bandicam 2018-06-22 17-00-21-941](https://user-images.githubusercontent.com/19775644/41804960-a81d022a-76a8-11e8-97e8-65677ec74eb1.jpg)
![bandicam 2018-06-22 17-01-27-797](https://user-images.githubusercontent.com/19775644/41804964-b93e5fd6-76a8-11e8-8a6c-b3628d853cf7.jpg)
![bandicam 2018-06-22 17-01-50-693](https://user-images.githubusercontent.com/19775644/41804965-bc231ff2-76a8-11e8-800c-e5de4ccd99ea.jpg)

# Labels:
gpu-corrupt-drawing
state-gameplay

**Comment by tjd2** [comment] 2018-06-23 09:22
Duplicate of #419
Is it different version?

**Closed** 2018-06-23 10:56 UTC
