### ISSUE TITLE
4B4E07D1 - Rumble Roses XX

### ISSUE THREAD

**Issue by vashdlad** [xenia-project/game-compatibility#1763] opened 2021-05-19 19:23 UTC
[Marketplace](http://marketplace.xbox.com/...)

Tested on https://github.com/xenia-project/xenia/commit/800db1aa49814e12044809b52ed69d0dd941a740

# Issues:
(Renders perfectly menus (including in-game menu. Upon selecting a fight, game crashes)

# Log:
[4B4E07D1 _xenia_log.zip](https://github.com/xenia-project/game-compatibility/files/6511125/4B4E07D1._xenia_log.zip)

# Screenshot(s):
![](Screenshot URL)

# Labels:
(state-gameplay)

**Comment by Gliniak** [comment] 2021-05-19 20:00
Duplicate of: https://github.com/xenia-project/game-compatibility/issues/770

**Closed by Gliniak** 2021-05-19 20:00 UTC
