### ISSUE TITLE
5454082B - Red Dead Redemption

### ISSUE THREAD

**Issue by iSynic** [xenia-project/game-compatibility#1140] opened 2019-01-22 00:14 UTC
[Marketplace](http://marketplace.xbox.com/en-US/Product/Red-Dead-Redemption/66acd000-77fe-1000-9115-d8025454082b)

Tested on (https://github.com/xenia-project/xenia/commit/9dd62c1e1553cf89bb7e3c4779163ec404b9599f")

# Issues:
Game runs well, as expected given the recent advances made. However, I'm getting a new issue I haven't seen reported. 

Strands of hair are various bright colors that change, like fiber optic lights. 

# Log:
[Log](https://mega.nz/#!XchCyQTZ!yhepDG5rSk1AWPfZY5nSltZ8AP96RUY76ivfutPVP_4)

# Screenshot(s):
![](https://i.imgur.com/fRjsIlj.jpg)
![](https://i.imgur.com/eUGkFww.jpg)

# Video
[Just a short one. ](https://youtu.be/AxO-XUz2EnI)

**Comment by Razzile** [comment] 2019-01-22 00:15
duplicate of https://github.com/xenia-project/game-compatibility/issues/108 
Please comment there

**Closed by Razzile** 2019-01-22 00:15 UTC
