### ISSUE TITLE
45410852 - The Lord of the Rings: Conquest

### ISSUE THREAD

**Issue by colt-smith** [xenia-project/game-compatibility#1817] opened 2021-09-04 06:16 UTC
https://marketplace.xbox.com/en-US/Product/LOTR-Conquest/66acd000-77fe-1000-9115-d80245410852

Tested on https://github.com/xenia-project/xenia/commit/master@6986d6c7e

# Issues:
When playing in game modes other than "Instant Action --> Conquest", the brightness is extremely high and cannot be adjusted. On all modes, death noises get stuck and repeat constantly and overlap. It's unplayable after a while. Screenshot attached is of the brightness issue, but can't really screenshot the noises. 

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/7109294/xenia.zip)

# Screenshot(s):
![Screenshot 2021-09-04 005513](https://user-images.githubusercontent.com/61435670/132084718-6700e593-303d-4554-bc14-ca313a00f8e3.png)

# Labels:
apu-slow gpu-shader-errors

**Comment by ZolaKluke** [comment] 2021-09-04 06:19
Duplicate of exisiting issue https://github.com/xenia-project/game-compatibility/issues/675

**Comment by illusion0001** [comment] 2021-09-04 06:22
Duplicate of #675

**Closed by illusion0001** 2021-09-04 06:22 UTC
