### ISSUE TITLE
545107E0 WWE Smackdown Vs Raw 2007 

### ISSUE THREAD

**Issue by ad556** [xenia-project/game-compatibility#1584] opened 2020-06-21 18:20 UTC
[Marketplace]N/A

Tested on xenia-project/xenia@9f789e0

ISSUES

Game randomly crashes, when in a match, used to crash also, in entrances but sometimes it does not.

Log:

[xenia.zip](https://github.com/xenia-project/game-compatibility/files/4810012/xenia.zip)

Labeles:

kernel-unimplemented-feature
state-crash-guest
state-crash-host
state-nothing
marketplace-unreleased
tech-engine-unreal

**Comment by Margen67** [comment] 2020-06-21 18:21
Duplicate of #1196.

**Closed** 2020-06-21 18:20 UTC
