### ISSUE TITLE
415607E1 - Call of Duty 3

### ISSUE THREAD

**Issue by vrpixel** [xenia-project/game-compatibility#1794] opened 2021-07-07 02:36 UTC
[Marketplace](https://marketplace.xbox.com/en-US/Product/Call-of-Duty-3/66acd000-77fe-1000-9115-d802415607e1)

Tested on https://github.com/xenia-project/xenia/commit/458e4e1a316d6e804cf2c19adc204b230ca75fcc

# Issues:
Unable to start a game in split screen. Game freezes for split second, but does not proceed further.

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/6773885/xenia.zip)

# Screenshot(s):
![https://i.imgur.com/RbrZnES.png]

# Labels:
tech-engine-iw

**Comment by illusion0001** [comment] 2021-07-07 04:12
Duplicate of #1320

**Closed by illusion0001** 2021-07-07 04:12 UTC
