### ISSUE TITLE
Broken Sound - 454108E6 - Skate 3

### ISSUE THREAD

**Issue by artik1ng** [xenia-project/game-compatibility#1617] opened 2020-08-20 13:51 UTC
# Marketplace
[Marketplace](https://marketplace.xbox.com/en-us/Product/Skate-3/66acd000-77fe-1000-9115-d802454108e6)

# Build
Build: detached / 6dc94d9154fa7e230f442017695a67e54c7e9a28 on Aug 16 2020

# Issues:
Everything works fine, except sound, if you have the black screen problem here is save file for you:
[454108E6.zip](https://github.com/xenia-project/game-compatibility/files/5103261/454108E6.zip)

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/5103220/xenia.zip)

# Config File:
[xenia.config.zip](https://github.com/xenia-project/game-compatibility/files/5103494/xenia.config.zip)

# Screenshot(s):
[YouTube Link](https://youtu.be/Q5De7w6mkoQ)

# Labels:
apu-garbage

**Comment by HighAssNeegah420** [comment] 2020-08-20 14:57
Theres already an entry for skate 3 so you'll prolly wanna post this there, that said, you are the fucking man for hookin it up with that save file, Now I can get in the game but I'm still getting small graphic glitches where some polygons, mostly on hair fade in and out of reality. as well as the game still seeming to crash whenever I try to input text to rename a skater or the team.

**Comment by artik1ng** [comment] 2020-08-20 15:07
> Theres already an entry for skate 3 so you'll prolly wanna post this there, that said, you are the fucking man for hookin it up with that save file, Now I can get in the game but I'm still getting small graphic glitches where some polygons, mostly on hair fade in and out of reality. as well as the game still seeming to crash whenever I try to input text to rename a skater or the team.
> 
> On a Ryzen 2600X and RX580 8GB

Im on RX580 8GB too, but my CPU is i5-4460, i don't have any video glitches.

**Comment by illusion0001** [comment] 2020-08-20 16:16
Duplicate of #201

**Closed** 2020-08-20 16:15 UTC
