### ISSUE TITLE
4D530A26 - Gears Of War - Judgment

### ISSUE THREAD

**Issue by afcmRamos** [xenia-project/game-compatibility#1805] opened 2021-08-01 18:49 UTC
[Marketplace](https://www.microsoft.com/en-us/p/gears-of-war-judgment/bshmmgrp84n4#activetab=pivot:overviewtab)

Tested on Master (detached/90c495050/Jul 26 2021)

# Issues:
The game loads, but crashs after 10 seconds. Sometimes I'm able to play for 2 to 3 minutes but it will crash again.

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/6913179/xenia.zip)

# Screenshot(s):
<img src="https://i.ibb.co/djH8DZS/2021-08-01-194736.jpg" alt="2021-08-01-194736" border="0">

# Labels:
state-crash-guest

**Comment by Prism019** [comment] 2021-08-01 18:50
duplicate of #585

**Closed by Prism019** 2021-08-01 18:50 UTC
