### ISSUE TITLE
415607D4 - Tony Hawk's American Wasteland

### ISSUE THREAD

**Issue by spectrumm** [xenia-project/game-compatibility#750] opened 2017-04-18 20:39 UTC
[Marketplace](http://marketplace.xbox.com/en-US/Product/American-Wasteland/66acd000-77fe-1000-9115-d802415607d4)

Tested on (https://ci.appveyor.com/project/benvanik/xenia/build/1.0.679-master)

# Issues:
Crashes instantly on both Vulkan and OpenGL

# Log:
[Log file]https://gist.github.com/spectrumm/83e3b1871e9bd05c9de39a2b94159012)

# Screenshot(s):
![](Screenshot URL)

# Labels:
state-nothing
state-crash
Possibly kernel related stuff, don't quite understand this fully yet.

**Comment by spectrumm** [comment] 2017-07-29 17:38
Game partially works, smooth framerate, renders all 3d basically perfect except for how it being offset to the left. Intro video starts flashing, click F5 to fix. Crashes on startup sometimes.

Game will freeze on a frame that looks like griptape zoomed in?

Screenshots (Sorry for low res):
![](https://image.prntscr.com/image/XGfPRpfsRsq96t74vrC55g.png)
![](https://image.prntscr.com/image/U7iTufUCTzGgAHai_nwv2Q.png)
![](https://image.prntscr.com/image/xyiIDQS2T0Wr4-iqprSBnA.png)
 "Griptape Issue" ?
![](https://image.prntscr.com/image/6qTuJJlJSK6ycCezzEEFIg.png

Tested on (https://ci.appveyor.com/project/benvanik/xenia/build/1.0.856-master)
[Log file]https://gist.github.com/spectrumm/b86fb91caedb45708486d793fbd0e577)

Labels:
state-gameplay

**Comment by spectrumm** [comment] 2017-07-29 17:42
Still crashes on vulkan.

**Comment by tnthps** [comment] 2017-09-29 09:59
I'm on the newest version, new to xenia. Experiencing crashes on full version of the game, but can kind of play my ripped version. I don't want to share the link, but you can find it on TPB by searching 'Tony Hawks American Wasteland [XBOX360] [RIP]' (1.06 GB)

![thaw_01](https://user-images.githubusercontent.com/32387521/31010952-494a59c6-a4d2-11e7-9858-23cf76b8bc52.png)
![thaw_02](https://user-images.githubusercontent.com/32387521/31010963-4ef7b544-a4d2-11e7-9eec-f9909d2b3ab3.png)
![thaw_03](https://user-images.githubusercontent.com/32387521/31010969-513b5cc0-a4d2-11e7-8ef3-1927b0edae1e.png)

At least in this version, menu loaded fine. All characters looked fine, except the created skater textures. I tested Chicago first, as it's a smaller map. It loaded completely fine. Gameplay was a little slow, but playable. Increasing the speed made it seem a little too fast. Tested East LA after that, loaded fine, but haven't tried other maps yet. There is an issue that causes the screen to go black while playing, but pausing the game and doing things in the options still work, and sound still works. Still, currently restarting each time to deal with the black screen, so it's still unplayable in my opinion, but very cool.

**Comment by Larxian** [comment] 2018-06-03 23:50
[https://www.youtube.com/watch?v=VFsdCgaxWfw](url)
Tested on build Build b35fe935 
Current issues : 
- Framerate jumping between locked 30 and locked 60, seems like a Vsync issue. 
- Game will crash upon any saving / loading save. 
- Buggy shadows, only character's shadows outline on some surfaces. 
- Music are bugged and will usualy stop a few seconds after starting, if this happen during gameplay the game will crash when the music stops. 
- Many audio effect missings. 
- Crashes very frequently, can be randomly during gameplay or when loading a level, after a cutscene etc... 
- When the screen goes black like at 1min 08, you have to go press start and immediatly go back to the main menu, otherwise the game will crash.

**Comment by Drive251** [comment] 2018-08-14 07:28
duplicated with https://github.com/xenia-project/game-compatibility/issues/202

**Comment by LilShootDawg** [comment] 2019-06-21 20:24
I found a temporary fix for the audio stopping crash which is to turn off the music in the options menu. I've tested it with the Vulkan and D3D12 branches. My 2 cents is that something is going wrong with the sound emulation in regards to the music.

**Comment by illusion98** [comment] 2019-07-08 12:53
Duplicate of https://github.com/xenia-project/game-compatibility/issues/202

**Closed by illusion98** 2019-07-08 12:53 UTC
Labels: apu-garbage, gpu-corrupt-drawing, kernel-save-file-errors, state-gameplay
