### ISSUE TITLE
45410961 - Need for Speed: Most Wanted 2012

### ISSUE THREAD

**Issue by 439bananas** [xenia-project/game-compatibility#2218] opened 2024-08-23 17:19 UTC
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch. (not MLBS/AlexVS/Canary/pull requests, etc)
- [X] This issue isn't for help (tech support) with Xenia, or a game.
- [x] I've checked if this game doesn't already have a compatibility report.

### Xenia version

https://github.com/xenia-project/xenia/commit/3d30b2eec3ab1f83140b09745bee881fb5d5dde2/

### Issues

Audio sounds either choppy or sped up in places
No gameplay, screen turns black after intro and game does not play
Surprisingly, Canary (even though this is master) has worse compatibility, locking up as it loads

Furthermore, please stop referring to "i.e." to mean "in example", it does not mean that! "i.e." is short for "id est", which is Latin for "that is". What you're looking for is "e.g.", which means "exempli gratia".

### Log

File size too big: 25 MB are allowed, 69 MB were attempted to upload.
Where can I paste this file? Will amend this section once I receive a response

### Screenshots

![image](https://github.com/user-attachments/assets/5c8d55b2-89d1-45a3-a362-d07ea614da81)

### Labels

apu-garbage, backwards-compatibility-unsupported, state-intro, state-load, state-title,

**Comment by Margen67** [comment] 2024-08-24 02:52
Duplicate of #501

**Closed by Margen67** 2024-08-24 02:52 UTC
