### ISSUE TITLE
41560817 - Call of Duty: Modern Warfare 2

### ISSUE THREAD

**Issue by Beta21Collector** [xenia-project/game-compatibility#392] opened 2016-01-16 18:26 UTC
[Marketplace](http://marketplace.xbox.com/en-US/Product/Modern-Warfare-2/66acd000-77fe-1000-9115-d80241560817)

Tested on xenia-project/xenia@9473f20c7fe39795e138602a48960d43eef28596

# Issues:
Videos have a green tint to them, Title screen (and menus) displays properly.

# Log:
[Log-too big for gist](https://drive.google.com/file/d/0B5bUIf8ElJ0qYXdwRWx4dHYwQTg/view?usp=sharing) (1.24 GB)

# Labels:
state-menus

**Comment by Razzile** [comment] 2016-01-16 18:28
when I tested mc2 a while ago the main menu was fully functional

**Comment by jc1999** [comment] 2016-02-01 20:39
There is a green tint on the .BIK screens but the menu works perfectly

**Comment by spectrumm** [comment] 2016-11-26 16:05
![image](https://cloud.githubusercontent.com/assets/23747820/20641532/758f1824-b3fa-11e6-9358-9510a02413c8.png)
Will come this far, only to hang.
I do hear audio from the ambient on the map. 
Same happens with my COD4

**Comment by spectrumm** [comment] 2017-08-21 19:24
Hangs at loading any map. Vulkan 1.0.987

**Comment by FranciscoCarlosJunior** [comment] 2020-04-25 13:54
Duplicate of #1040

**Closed** 2020-04-25 22:18 UTC
Labels: issue-superseded
