### ISSUE TITLE
4D5607D1 - DEADLY PREMONITION

### ISSUE THREAD

**Issue by LuismaSP89** [xenia-project/game-compatibility#1544] opened 2020-05-02 02:22 UTC
[Marketplace](http://marketplace.xbox.com/...)

Tested on https://github.com/xenia-canary/xenia-canary/commit/660559bd372e34f62979b43fc9bf23b81f236037

# Issues:
Language selection is not  working properly. I have a copy of deadly premonition which already includes multi5 languages (Spanish in my case) but for some reason, the game is all the time on english. This is the only game I got problems with the xenia's internal language selector. (Using canary and changed the values for language and country in config) all other games works as it shoud and shows in spanish.

My specs:
Windows 10 x64
i7 4790k
GTX 970
16GB DDR3

# Log:
Compress your logfile into a compressed folder named xenia.zip and then click and drag it here (
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/4566939/xenia.zip)
[xenia-canary-config.zip](https://github.com/xenia-project/game-compatibility/files/4566940/xenia-canary-config.zip)

# Labels:
- state-gameplay

**Comment by LuismaSP89** [comment] 2020-05-02 02:23
My specs:

Windows 10 x64
i7 4790k
GTX 970
16GB DDR3

**Comment by Margen67** [comment] 2020-05-02 04:17
Duplicate of #811

**Closed by Margen67** 2020-05-02 04:17 UTC
Labels: issue-duplicate
