### ISSUE TITLE
4D53082D - gears of war 2  

### ISSUE THREAD

**Issue by dj--alex** [xenia-project/game-compatibility#1404] opened 2019-09-07 07:36 UTC
https://marketplace.xbox.com/ru-RU/Product/Gears-of-War-2/66acd000-77fe-1000-9115-d8024d53082d?nosplash=1

Tested on https://github.com/xenia-project/xenia/commit/master
Custom builds also have all of this bugs. 

# Issues:
Cannot start Solo campaign - Error network layer 
works only training.
Save games no work.
Graphics glitches over screen
Used Linux Mint 19.1x64 GTX1080 Nvidia driver 430, Vulkan
# Log:
Compress your logfile into a compressed folder named xenia.zip and then click and drag it here [xenia.log.tar.gz](https://github.com/xenia-project/game-compatibility/files/3586380/xenia.log.tar.gz)

# Screenshot(s):
https://sun9-52.userapi.com/c855016/v855016949/e1340/jh9z4ylzGCU.jpg
https://sun9-59.userapi.com/c855016/v855016949/e134a/VJHcSkVN-cg.jpg

# Labels:
(recommended labels)
gpu-corrupt-drawing  gpu-shader-errors

**Comment by Triang3l** [comment] 2019-09-07 08:02
Duplicate of #163.

**Closed by Triang3l** 2019-09-07 08:02 UTC

**Comment by Triang3l** [comment] 2019-09-07 08:04
Reports of graphics glitches from the old unmaintained rendering layer are ignored, by the way.

**Comment by Triang3l** [comment] 2019-09-07 08:05
(Custom builds too)

**Comment by dj--alex** [comment] 2019-09-07 14:16
I use 1 official and 5 custom builds with SAME result.
Vulkan - is only one way to run game on linux
You really want to drop Linux support???

**Comment by Triang3l** [comment] 2019-09-07 20:07
We don't want to drop it — though we can't really drop what we don't even have. The Vulkan renderer isn't maintained because nobody is just spending time on it, it was just faster to experiment on Direct3D, and Vulkan didn't have rasterizer-ordered views back when I started the new renderer (though I wasn't aware of them when I decided to use D3D, simplicity and fast iteration was the reason because back then I didn't even have any vision of how X360 GPU emulation needed to be done). I do want to port the new architecture do Vulkan, but I don't have much free time and interest, also considering it's totally not the only missing part that would be needed to run Xenia on Android.
