### ISSUE TITLE
424507D1 - Kingdom Under Fire: Circle of Doom

### ISSUE THREAD

**Issue by DarthSidious666** [xenia-project/game-compatibility#1466] opened 2019-11-19 19:32 UTC
[Marketplace](https://marketplace.xbox.com/en-us/Product/KUF-Circle-of-Doom/66acd000-77fe-1000-9115-d802424507d1)

Tested on Build: https://github.com/xenia-project/xenia/commit/8ba6f3fc37e6f99e3fd232384388cb73b3494bae on Nov 10 2019

# Issues:
state-guest-crash

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/3865698/xenia.zip)

# Screenshot(s):
![xenia-error](https://user-images.githubusercontent.com/57962477/69179241-1dbdb200-0b03-11ea-9ac1-df39b2638a3b.png)

# Labels:
state-guest-crash

**Comment by illusion98** [comment] 2019-11-19 19:33
Duplicate of https://github.com/xenia-project/game-compatibility/issues/917

**Closed** 2019-11-19 19:33 UTC
