### ISSUE TITLE
565707D0 - Lolipop Chainsaw

### ISSUE THREAD

**Issue by MidNightBear24** [xenia-project/game-compatibility#1828] opened 2021-09-20 00:21 UTC
[Marketplace](https://marketplace.xbox.com/en-US/Product/Lollipop-Chainsaw/66acd000-77fe-1000-9115-d802565707d0)

Tested on https://github.com/xenia-canary/xenia-canary/commit/9c74b4caba5a2f35f40c20ac555abe9e21e02b93

# Issues:
I have yet to complete the game but from the 2 hours or so of playtime I have in it the game is very playable. There are of course bugs such as audio glitching and graphical pop ins from time to time. The first screenshot I have below is of the graphical pop in. It only pops up for a second or two and then disappears. Aside from that the game plays well and I'm able to get around 30fps even on my lower end system. 

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/7193173/xenia.zip)

# Screenshot(s):
![133947591-2b8497a1-fff4-44ec-85d5-1e6b4cc0cc49](https://user-images.githubusercontent.com/90889644/133947739-4e778747-e0fa-4067-ab59-a1e1510cbbb4.png)
![133947612-7c7f9892-2078-4aca-bcfd-1378588e3a2d](https://user-images.githubusercontent.com/90889644/133947744-efd5885e-986c-4920-a266-62810844eabf.png)

# Labels:
state-gameplay
gpu-drawing-corrupt
apu-slow

**Comment by Gliniak** [comment] 2021-09-20 06:21
Duplicate of #983 

Do not report canary status in official compatibility report

**Closed by Gliniak** 2021-09-20 06:21 UTC

**Comment by MidNightBear24** [comment] 2021-09-20 22:30
> Duplicate of #983
> 
> Do not report canary status in official compatibility report

As I responded with the resident evil 4 issue report I test all my games with both canary and master that way I can see if either has differing issues and was not sure which one to use in the report. And from what you said about the duplicate I think you should look into https://github.com/xenia-project/game-compatibility/issues/983 because if you search the name "lolipop chainsaw" the only thing that will show up is the issue made by me, however if you search "983" it will show up. Not sure if that's a glitch or something else.

**Comment by EpicFoxx64** [comment] 2021-09-20 22:45
> > Duplicate of #983
> > Do not report canary status in official compatibility report
> 
> As I responded with the resident evil 4 issue report I test all my games with both canary and master that way I can see if either has differing issues and was not sure which one to use in the report. And from what you said about the duplicate I think you should look into #983 because if you search the name "lolipop chainsaw" the only thing that will show up is the issue made by me, however if you search "983" it will show up. Not sure if that's a glitch or something else.

Not to sound rude but you might not have found the old issue because you only used one 'L' in lollipop. Spelling it with 2 allows you to find the original issue
