### ISSUE TITLE
464F0802 - Terraria

### ISSUE THREAD

**Issue by PcDivision** [xenia-project/game-compatibility#502] opened 2016-07-04 05:10 UTC
[Marketplace](http://marketplace.xbox.com/en-au/Product/Terraria-Xbox-360-Edition/66acd000-77fe-1000-9115-d8025841128f)

Tested on (https://github.com/benvanik/xenia/commit/3d1d4dea47dd95117befe436ed292ad79ca5ee13)

# Issues:
(Does Not Load)

# Log:
[Log file](https://gist.github.com/PcDivision/32ba3cee6ff151ba8a9532ab688beef0)

# Screenshot(s):
![](http://puu.sh/pPAmT/4105b1210b.png)

# Labels:
(state-nothing)

**Comment by Razzile** [comment] 2016-07-04 06:02
terarria is one of those games built using the .NET runtime I think. xenia will never be able to emulate this (unless a contributor adds what is essentially a modified .NET runtime to support these titles)

**Comment by DrChat** [comment] 2016-07-12 02:37
Possibly a duplicate of #199

**Comment by Razzile** [comment] 2016-07-12 07:17
yes it is. guy used the wrong ID

**Closed by Razzile** 2016-07-12 07:17 UTC
Labels: state-nothing
