### ISSUE TITLE
58410955 - Banjo-Tooie

### ISSUE THREAD

**Issue by pedrosenedesi** [xenia-project/game-compatibility#1807] opened 2021-08-10 02:01 UTC
[Marketplace](https://marketplace.xbox.com/en-US/Product/Banjo-Tooie/66acd000-77fe-1000-9115-d80258410955)

Tested on https://github.com/xenia-project/xenia/commit/4861022158ff02bf51660dcf1dbb33eb1ad4cded

# Issues:
Game runs great, only has some audio issues, as shown on the video. Witchyworld seems to be the most affected level, although I have had some issues on Glitter Gulch Mine too. Audio pops, and on the whole game Kazooie's long beak attack audio doesn't play completely, also shown on video.

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/6958402/xenia.zip)

# Screenshot(s):
https://www.youtube.com/watch?v=l94llQPlVtg

# Labels:
apu-slow, apu-garbage

**Comment by illusion0001** [comment] 2021-08-10 02:32
Duplicate of #

**Comment by illusion0001** [comment] 2021-08-10 02:33
Duplicate of #207

**Closed by illusion0001** 2021-08-10 02:32 UTC
