### ISSUE TITLE
A World of Keflings

### ISSUE THREAD

**Issue by Potatoified** [xenia-project/game-compatibility#2003] opened 2022-09-01 21:02 UTC
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch. (not MLBS/AlexVS/Canary/pull requests, etc)
- [X] This issue isn't for help (tech support) with Xenia, or a game.
- [X] I've checked if this game doesn't already have a compatibility report.

### Xbox 360 Marketplace link

https://marketplace.xbox.com/en-US/Product/A-World-of-Keflings/66acd000-77fe-1000-9115-d802584109db

### Xenia version

https://github.com/xenia-canary/xenia-canary/commit/5cb86f7173bef8af18c6f1f99e337a1f804a77f7/

### Issues

Loads into the game's Main Menu, after showing startup screens, but only on the 
xenia-canary build (0.0.0.5788/5cb86f71/Feb 23 2020)
When loaded into the game menu, settings and other things that do not require an xbox live account are functional, but when you click Play Game, and then create a New Save for any game mode, it loads until the kefling hits the middle of the screen and the game crashes immediately every time. No other builds I've tested seem to have this working, 
Here's an image of what I am talking about. It crashes in the middle of the loading screen.
This game has a compatibility report, but hasn't been touched for months, and my comment isn't being noticed, so I'd like to bring more attention to patching this issue through making a new, updated issue, as the old issue's state of the game is still stuck in the intro. As of now, the only way to play this game is through this SPECIFIC xenia-canary build on github, which is through SEVERAL forks and VERY hard to find.

### Log

https://github.com/xenia-project/game-compatibility/files/9457234/xenia.zip

### Screenshots

![image](https://user-images.githubusercontent.com/40216635/188011764-0c2a89c8-40cc-4fc0-9ace-463cfda6fd78.png)

### Labels

state-menus

**Comment by Margen67** [comment] 2022-09-01 21:03
Duplicate of #303

**Closed** 2022-09-01 21:02 UTC
Labels: issue-invalid
