### ISSUE TITLE
54510865 - de Blob 2

### ISSUE THREAD

**Issue by Sanic1239** [xenia-project/game-compatibility#1649] opened 2020-11-19 01:29 UTC
[Marketplace](https://marketplace.xbox.com/en-US/Product/de-Blob-2/66acd000-77fe-1000-9115-d80254510865)

Build: detached / b7ba3051f22d62aff0795d43e5d5ea7662864b24 on Nov 16 2020
Tested on https://github.com/xenia-project/xenia/commit/b7ba3051f22d62aff0795d43e5d5ea7662864b24

Issues:

-Broken Title Screen Music
-Broken/Crackling In-Game Music (I think)
-Glitched Line of Pixels (Don't know the actual name but you'll see it)
-Controller Continues Vibrating Even When Event is Over (Unless thats a global error in Xenia)

Screenshot(s):

![Capture](https://user-images.githubusercontent.com/40549579/99610103-03444000-29c6-11eb-9206-f132cd07ce95.PNG)
![Capture2](https://user-images.githubusercontent.com/40549579/99610117-09d2b780-29c6-11eb-846d-9df17b9b48f5.PNG)
![Capture3](https://user-images.githubusercontent.com/40549579/99610122-0dfed500-29c6-11eb-84cc-f9879d2029f1.PNG)
![Capture4](https://user-images.githubusercontent.com/40549579/99610134-13f4b600-29c6-11eb-8add-4426c1a23b44.PNG)

(Sorry, don't know how to add labels)

**Comment by Sanic1239** [comment] 2020-11-19 18:20
And if I upload a log file, does it contain any personal information of your device?

**Comment by Etokapa** [comment] 2020-11-22 23:10
Dupe of #1375

**Comment by Sanic1239** [comment] 2020-11-23 04:38
Whoops sorry, for some reason it didn't show up in the search results..

**Comment by Gliniak** [comment] 2020-11-23 08:54
Same 😅 I'm closing this one then. You can still copy-paste your input to original issue

Duplicate #1375

**Closed by Gliniak** 2020-11-23 08:54 UTC
Labels: apu-garbage, gpu-drawing-corrupt, state-gameplay
