### ISSUE TITLE
58410846 - Alien Hominid HD 

### ISSUE THREAD

**Issue by Sterophonick** [xenia-project/game-compatibility#1332] opened 2019-07-15 03:09 UTC
58410846 - Alien Hominid HD 
https://marketplace.xbox.com/en-us/Product/Alien-Hominid-HD/66acd000-77fe-1000-9115-d80258410846

Tested on https://github.com/xenia-project/xenia/commit/35c8b66c939fc35b500764b940b2c3ba9f9b91d3

# Issues:
The looping of the music does not work, and the text is not rendered correctly

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/3390745/xenia.zip)

# Screenshot(s):
![Capture](https://user-images.githubusercontent.com/34801996/61193947-41fc1480-a673-11e9-8829-08446e125468.PNG)

**Comment by Margen67** [comment] 2019-07-15 03:10
Duplicate of #26

**Closed by Margen67** 2019-07-15 03:10 UTC
