### ISSUE TITLE
41560815 - Spider Man: Web of Shadows

### ISSUE THREAD

**Issue by EmeraldaChaos** [xenia-project/game-compatibility#1829] opened 2021-09-20 06:11 UTC
[Marketplace](http://marketplace.xbox.com/...)

Tested on https://github.com/xenia-project/xenia/commit/360e2f541

# Issues:
The game boots to the title screen and the demo plays perfectly fine as far as I can tell but when actually trying to start the game, it crashes with an error and that is it.

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/7193820/xenia.zip)

# Screenshot(s):
https://i.imgur.com/FuqcizV.png
https://i.imgur.com/e879Law.png 
https://i.imgur.com/5Fv3jmP.png

# Labels:
state-title
marketplace-unlisted

**Comment by Gliniak** [comment] 2021-09-20 06:22
Duplicate of #916

**Closed by Gliniak** 2021-09-20 06:22 UTC
