### ISSUE TITLE
Mercenaries 2 - missing water, graphical artifacts with smoke and explosions

### ISSUE THREAD

**Issue by j4m84** [xenia-project/game-compatibility#2047] opened 2023-03-02 23:37 UTC
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch. (not MLBS/AlexVS/Canary/pull requests, etc)
- [X] This issue isn't for help (tech support) with Xenia, or a game.
- [X] I've checked if this game doesn't already have a compatibility report.

### Xenia version

https://github.com/xenia-project/xenia/commit/.../

### Issues

This game worked without artifacts, but it was problematic to save on version c43ccc0 on Dec 4, 2019, after this version, water disappeared in the game and the smoke became distorted in subsequent versions and before the latest.

### Log

[normal version.zip](https://github.com/xenia-project/game-compatibility/files/10876697/normal.version.zip)
[no water version.zip](https://github.com/xenia-project/game-compatibility/files/10876698/no.water.version.zip)

### Screenshots

![Снимок экрана (96)](https://user-images.githubusercontent.com/126829079/222593133-8e9bcaaa-eaec-4884-b7a6-b5133cf9b296.png)
![Снимок экрана (97)](https://user-images.githubusercontent.com/126829079/222593143-4d5c8c50-5a6c-4a19-87ea-f1f2a1f61e1b.png)

### Labels

state-gameplay

**Comment by Margen67** [comment] 2023-03-03 00:03
Duplicate of #606

**Closed by Margen67** 2023-03-03 00:03 UTC
