### ISSUE TITLE
53510823 - Rise of the Tomb Raider

### ISSUE THREAD

**Issue by Kattus** [xenia-project/game-compatibility#368] opened 2015-12-21 19:12 UTC
[Marketplace](http://marketplace.xbox.com/en-US/Product/Rise-of-the-Tomb-Raider/66acd000-77fe-1000-9115-d80253510823)
![Screenshot](http://i.imgur.com/laSvGpO.png)
Tested on benvanik/xenia@82ddd0430fe3792e8ce6e23dea161e5832b4f5f8

Plays intros (not sure if all), then crashes.
[Log output](https://gist.github.com/Kattus/17fa9393f016a6e1dc6c)

state-load gpu-corrupt-drawing

**Comment by sephiroth99** [comment] 2015-12-22 08:37
Duplicate of #247

**Comment by Razzile** [comment] 2015-12-22 09:07
yea https://github.com/xenia-project/game-compatibility/issues/247 seems better

**Closed by Razzile** 2015-12-22 09:07 UTC
Labels: gpu-corrupt-drawing, state-load
