### ISSUE TITLE
4E4D0860 - Dragon Ball Z Battle of Z

### ISSUE THREAD

**Issue by AubbyLobby** [xenia-project/game-compatibility#1778] opened 2021-06-05 22:16 UTC
[Marketplace](https://marketplace.xbox.com/en-US/Product/DBZ-Battle-of-Z/66acd000-77fe-1000-9115-d8024e4d0860)

Tested on https://github.com/xenia-project/xenia/commit/10ff77a24f25827021a900b730e8868b878b1f14

# Issues:
When starting the game, after the developer logo credits are finished, Xenia pauses itself.

Most common error:
"The guest has crashed. Xenia has now paused itself. A crash dump has been written into the log."

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/6603311/xenia.zip)

# Screenshot(s):
https://media.discordapp.net/attachments/308207592482668545/850188874919444520/unknown.png?width=1121&height=670
# Labels:
https://github.com/xenia-project/game-compatibility/labels/state-load

**Comment by illusion0001** [comment] 2021-06-05 22:22
Duplicate of #871

**Closed by illusion0001** 2021-06-05 22:22 UTC
