### ISSUE TITLE
415608A7 - Prototype 2

### ISSUE THREAD

**Issue by Ashh131** [xenia-project/game-compatibility#2216] opened 2024-08-19 17:03 UTC
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch. (not MLBS/AlexVS/Canary/pull requests, etc)
- [X] This issue isn't for help (tech support) with Xenia, or a game.
- [X] I've checked if this game doesn't already have a compatibility report.

### Xbox 360 Marketplace link

https://www.xbox.com/en-GB/games/store/prototype2/C3H56C11VWHM

### Xenia version

3d30b2eec3ab1f83140b09745bee881fb5d5dde2

### Issues

Game does not get passed the opening screen, Guest crash

### Log

[xenia.log](https://github.com/user-attachments/files/16663272/xenia.log)

### Screenshots

![Screenshot 2024-08-19 175419](https://github.com/user-attachments/assets/bc72518a-d487-4439-a854-b7c57b393ae8)

### Labels

state-crash-guest

**Comment by Margen67** [comment] 2024-08-20 00:12
Duplicate of #670

**Closed by Margen67** 2024-08-20 00:12 UTC
