### ISSUE TITLE
4E4D07F0 - Splatterhouse

### ISSUE THREAD

**Issue by Rafael-code-maker** [xenia-project/game-compatibility#1679] opened 2020-12-11 15:18 UTC
Marketplace : https://marketplace.xbox.com/pt-BR/Product/SPLATTERHOUSE/66acd000-77fe-1000-9115-d8024e4d07f0

Build : 9349cf4ff4c37caa2f2b2a27bc51111a79c0b561 on Dec  8 2020

# Issues:

The game runs almost fine, but i cant save it.

# Log:

[xenia.zip](https://github.com/xenia-project/game-compatibility/files/5679951/xenia.zip)

# Screenshot(s):

![Capturar](https://user-images.githubusercontent.com/18178966/101920500-a7c33780-3baa-11eb-9a6b-6ab29c1d410a.PNG)

# Labels:
kernel-save-file-errors

**Comment by Triang3l** [comment] 2020-12-11 15:42
Duplicate of #810, contents moved there.

**Closed by Triang3l** 2020-12-11 15:42 UTC
