### ISSUE TITLE
Guitar Hero Metallica PC - Xenia Xbox 360 Emulator - In Game

### ISSUE THREAD

**Issue by brenoyure** [xenia-project/game-compatibility#410] opened 2016-02-02 19:30 UTC
[https://www.youtube.com/watch?v=_bQpg1euvDk]

**Comment by gibbed** [comment] 2016-02-02 19:36
Duplicate of #185. This is the second time you've done this, please put more effort into your posts.

**Closed by gibbed** 2016-02-02 19:36 UTC
