### ISSUE TITLE
58410888 - Triggerheart Exelica

### ISSUE THREAD

**Issue by Tea-Fox** [xenia-project/game-compatibility#1630] opened 2020-10-04 07:40 UTC
[Marketplace](https://marketplace.xbox.com/en-us/Product/Triggerheart-Exelica/66acd000-77fe-1000-9115-d80258410888)

Tested on https://github.com/xenia-project/xenia/commit/e0916be5cd6458bf80cf2a09e0a0bf02fbccf319

# Issues:
When playing the game, the music will play at first, but after a bit it will stop playing. Sound effects and character voices are not affected and will continue to play. When reaching the Boss, the Boss music will start playing however, same things happen will any new level, music will play for a while, then suddenly stop and remain silent until a new track gets played.
The gameplay itself is unaffected by this. The screenshot shows the exact place in the first level where the music stops (shortly after the large tank surrounded by smaller tanks, about a minute and a half into the stage).

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/5322782/xenia.zip)

# Screenshot(s):
![](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/9b58a263-a3f3-4c0d-9e13-c895025c6a82/de69kya-93c01077-9f62-4207-b58a-58b9e5edc817.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOiIsImlzcyI6InVybjphcHA6Iiwib2JqIjpbW3sicGF0aCI6IlwvZlwvOWI1OGEyNjMtYTNmMy00YzBkLTllMTMtYzg5NTAyNWM2YTgyXC9kZTY5a3lhLTkzYzAxMDc3LTlmNjItNDIwNy1iNThhLTU4YjllNWVkYzgxNy5wbmcifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6ZmlsZS5kb3dubG9hZCJdfQ.bzL-S9p__njnMbyE3je9ohAonPNFNyKjkHagLDKIuVQ)

# Labels:
apu-silent, apu-garbage, state-playable

**Comment by Prism019** [comment] 2020-10-04 08:07
duplicate of #1358

**Closed by Prism019** 2020-10-04 08:07 UTC
