### ISSUE TITLE
415608A7 - PROTOTYPE®2

### ISSUE THREAD

**Issue by sanskar127** [xenia-project/game-compatibility#2187] opened 2024-05-01 08:51 UTC
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch. (not MLBS/AlexVS/Canary/pull requests, etc)
- [x] This issue isn't for help (tech support) with Xenia, or a game.
- [X] I've checked if this game doesn't already have a compatibility report.

### Xbox 360 Marketplace link

"PROTOTYPE 2" site:marketplace.xbox.com/en-US/Product/PROTOTYPE-2/66acd000-77fe-1000-9115-d802415608a7

### Xenia version

https://github.com/xenia-project/xenia/commit/5ca173cd4f4bfc941fe06250297d518e41dfd7b7/

### Issues

Black Screen in main game but, other things are working fine.

### Log

[xenia.log.zip](https://github.com/xenia-project/game-compatibility/files/15175257/xenia.log.zip)

### Screenshots

![Screenshot](https://github.com/xenia-project/game-compatibility/assets/54498345/a61817b7-0ebc-4d80-9315-5403c4ca5902)

### Labels

state-menus, gpu-drawing-missing, tech-engine-titanium

**Comment by Margen67** [comment] 2024-05-01 10:51
Duplicate of #670

**Closed by Margen67** 2024-05-01 10:51 UTC
