### ISSUE TITLE
5841125E - Joyride Turbo

### ISSUE THREAD

**Issue by BootSwitch** [xenia-project/game-compatibility#1602] opened 2020-07-22 09:25 UTC
[Marketplace](https://www.microsoft.com/en-gb/p/joy-ride-turbo/c1zwh2bz9tsf?activetab=pivot:overviewtab)

Tested on https://github.com/xenia-project/xenia/commit/9418f3f2c5fb3b98421cca7f71506bc02fa48735

# Issues:

- Sometimes the text can get buggy and corrupted (can be fixed by pressing F5).
- The game renders at a super low resolution (the GUI is fine, just the actual graphics in game).
- I can't unlock the full version.

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/4959169/xenia.zip)

# Screenshots:

https://i.imgur.com/45puN07.jpeg
https://i.imgur.com/YWUsbhc.png
https://i.imgur.com/000RMpw.jpeg

# Labels:
gpu-drawing-corrupt state-gameplay

**Comment by Gliniak** [comment] 2020-07-22 09:37
Duplicate of #1424

**Closed by Gliniak** 2020-07-22 09:37 UTC
