### ISSUE TITLE
5451087D - UFC Undisputed 3

### ISSUE THREAD

**Issue by tipleavalentin** [xenia-project/game-compatibility#1495] opened 2020-02-16 12:28 UTC
[Marketplace](https://marketplace.xbox.com/en-US/Product/UFC-Undisputed-3/66acd000-77fe-1000-9115-d802585709a1)

Tested on https://github.com/xenia-project/xenia/commit/8ec813de8248fbe4fb31882930747428ebb4de0f

# Issues:
The game works fine, no graphics issues, until freezes on the loading screen before the match starts.

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/4209733/xenia.zip)

# Screenshot(s):
![](https://user-images.githubusercontent.com/14072036/74604579-083b3280-50c8-11ea-970a-3f59674807b7.png)

# Labels:
state-menus

**Comment by Gliniak** [comment] 2020-10-19 07:19
Duplicate of: #1081

**Closed by Gliniak** 2020-10-19 07:19 UTC
Labels: state-menus
