### ISSUE TITLE
4D530AA4 - Forza Horizon 2 

### ISSUE THREAD

**Issue by TomZak7** [xenia-project/game-compatibility#2215] opened 2024-08-16 16:04 UTC
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch. (not MLBS/AlexVS/Canary/pull requests, etc)
- [X] This issue isn't for help (tech support) with Xenia, or a game.
- [X] I've checked if this game doesn't already have a compatibility report.

### Xenia version

https://github.com/xenia-project/xenia/commit/3d30b2eec3ab1f83140b09745bee881fb5d5dde2/

### Issues

The game gets through menus but after a few cutscences when you start playing it crashes.

### Log

[xenialog.zip](https://github.com/user-attachments/files/16639046/xenialog.zip)

### Screenshots

![Screenshot 2024-08-16 162219](https://github.com/user-attachments/assets/a5ae595c-2054-45cd-a66f-ff446008ace2)
![Screenshot 2024-08-16 162224](https://github.com/user-attachments/assets/c5c3a8db-0820-4511-a046-0f061f41a21c)
![Screenshot 2024-08-16 162231](https://github.com/user-attachments/assets/33172b75-f855-438e-b619-21d8afeb1e2d)
![Screenshot 2024-08-16 162250](https://github.com/user-attachments/assets/6b491985-0520-49f5-ba58-47b4c579aad0)
![Screenshot 2024-08-16 162403](https://github.com/user-attachments/assets/805584cb-f854-4a8d-9ffb-430c251e46cb)

### Labels

backwards-compatibility-unsupported, state-menus,

**Comment by Margen67** [comment] 2024-08-18 10:37
Duplicate of #514

**Closed by Margen67** 2024-08-18 10:37 UTC
