### ISSUE TITLE
545107D1 - Saint Row

### ISSUE THREAD

**Issue by alonegreen** [xenia-project/game-compatibility#1772] opened 2021-05-29 21:54 UTC
[Marketplace](http://marketplace.xbox.com/en-US/Product/Saints-Row/66acd000-77fe-1000-9115-d802545107d1)

Tested on https://github.com/xenia-project/xenia/commit/fbc31652e0e31b94da547195623fd53252d513f6

# Issues:
Can't play the game because it crashed the game way to fast.(With in 5mins or sooner)

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/6565359/xenia.zip)

# Screenshot(s):
Can be added if needed.

# Labels:
Can be wrong here not sure what labels to use!
(state-crash-xna-WONTFIX)

**Comment by illusion0001** [comment] 2021-05-29 22:00
Duplicate of #104

**Closed by illusion0001** 2021-05-29 22:00 UTC
