### ISSUE TITLE
4156081C - Call of Duty: World at War

### ISSUE THREAD

**Issue by ryemck** [xenia-project/game-compatibility#1055] opened 2018-08-05 12:32 UTC
[Marketplace](http://marketplace.xbox.com/en-us/Product/Call-of-Duty-WaW/66acd000-77fe-1000-9115-d8024156081c)

Tested on https://ci.appveyor.com/api/projects/benvanik/xenia/artifacts/xenia-master.zip?branch=master&job=Configuration%3A%20Release

# Issues:
When trying to do any of these, the emulator locks up and I have to close it via Task Manager:

- Access the Credits (black screen after loading)

- Access the Multiplayer Area (see screenshot)

- Start a new single player or co-op campaign (black screen after loading)

# Log:

[xenia.zip](https://github.com/xenia-project/game-compatibility/files/2260303/xenia.zip)

# Screenshot(s):
![Here]( (black screen after loading))

# Labels:
(recommended labels)
idk :S

**Comment by ryemck** [comment] 2018-08-05 12:32
Screenshot here sorry idk what happened there: https://imgur.com/a/VLfZCea

**Comment by bdeimos** [comment] 2018-08-05 12:43
Duplicate of #249

**Comment by Ulquiorr4-Cifer** [comment] 2018-08-05 19:17
That's not how you reference build you used @ryemck

**Comment by spectrumm** [comment] 2018-08-19 22:13
I can get in game but it locks at select team.

**Comment by spectrumm** [comment] 2018-08-19 22:16
![image](https://user-images.githubusercontent.com/23747820/44313781-578a9f00-a40e-11e8-9811-6fa7b22dc4cc.png)

**Closed** 2019-01-01 16:18 UTC
