### ISSUE TITLE
58410A9F - The Fancy Pants Adventures

### ISSUE THREAD

**Issue by spectrumm** [xenia-project/game-compatibility#753] opened 2017-04-20 17:41 UTC
[Marketplace](http://marketplace.xbox.com/en-US/Product/The-Fancy-Pants-Adventures/66acd000-77fe-1000-9115-d80258410a9f)

Tested on (https://ci.appveyor.com/project/benvanik/xenia/build/1.0.681-master)

# Issues:
Absolutely nothing happens. Gray screen

# Log:
[Log file](https://gist.github.com/spectrumm/c3805f15926f63c7ccb00b316f946f41)

# Screenshot(s):
![](https://cdn.discordapp.com/attachments/246740949739372544/304672842962960384/unknown.png)

# Labels:
state-nothing

**Comment by spectrumm** [comment] 2017-04-20 17:41
Used both Vulkan and OpenGL but only uploaded VK log

**Comment by Sleepy93** [comment] 2017-04-20 20:21
Just checked the log file and I saw these errors:

w> 00000028 ERROR: fn export referenced GetProcAddressByOrdinal(0AFF(XamPartyGetUserList)) is not implemented
w> 00000028 ERROR: XexGetProcedureAddress ordinal not found!
i> 00000028 RtlNtStatusToDosError(C0000263)
i> 00000028 RtlNtStatusToDosError => 7F
w> 00000028 ERROR: fn export referenced GetProcAddressByOrdinal(0B00(XamPartySendGameInvites)) is not implemented
w> 00000028 ERROR: XexGetProcedureAddress ordinal not found!
i> 00000028 RtlNtStatusToDosError(C0000263)
i> 00000028 RtlNtStatusToDosError => 7F
w> 00000028 ERROR: fn export referenced GetProcAddressByOrdinal(0B0B(XamPartySetCustomData)) is not implemented
w> 00000028 ERROR: XexGetProcedureAddress ordinal not found!
i> 00000028 RtlNtStatusToDosError(C0000263)
i> 00000028 RtlNtStatusToDosError => 7F
w> 00000028 ERROR: fn export referenced GetProcAddressByOrdinal(0B10(XamPartyGetBandwidth)) is not implemented
w> 00000028 ERROR: XexGetProcedureAddress ordinal not found!
i> 00000028 RtlNtStatusToDosError(C0000263)
i> 00000028 RtlNtStatusToDosError => 7F
w> 00000028 ERROR: fn export referenced GetProcAddressByOrdinal(0305(XamShowPartyUI)) is not implemented
w> 00000028 ERROR: XexGetProcedureAddress ordinal not found!
i> 00000028 RtlNtStatusToDosError(C0000263)
i> 00000028 RtlNtStatusToDosError => 7F
w> 00000028 ERROR: fn export referenced GetProcAddressByOrdinal(030B(XamShowCommunitySessionsUI)) is not implemented
w> 00000028 ERROR: XexGetProcedureAddress ordinal not found!
i> 00000028 RtlNtStatusToDosError(C0000263)
i> 00000028 RtlNtStatusToDosError => 7F
F> 00000028 Device::ResolvePath(\media\data360)
i> 00000028 RtlNtStatusToDosError(C000000F)
i> 00000028 RtlNtStatusToDosError => 2
F> 00000028 Device::ResolvePath(\media\datacommon)
i> 00000028 RtlNtStatusToDosError(C000000F)
i> 00000028 RtlNtStatusToDosError => 2
 
So I think the labels are:

-  state-nothing
- kernel-unimplemented-features

Is it correct?

**Comment by Drive251** [comment] 2018-08-14 07:26
duplicated with https://github.com/xenia-project/game-compatibility/issues/40

**Comment by illusion98** [comment] 2019-07-08 00:21
Duplicate of https://github.com/xenia-project/game-compatibility/issues/40

**Closed by illusion98** 2019-07-08 00:21 UTC
Labels: state-nothing
