### ISSUE TITLE
5454082B - Red Dead Redemption GOTY Edition

### ISSUE THREAD

**Issue by yokotsumo** [xenia-project/game-compatibility#1406] opened 2019-09-08 20:52 UTC
5454082B - Red Dead Redemption GOTY Edition

[Marketplace](http://marketplace.xbox.com/en-US/Product/Red-Dead-Redemption/66acd000-77fe-1000-9115-d8025454082b)

Tested on https://ci.appveyor.com/api/projects/benvanik/xenia/artifacts/xenia-master.zip?branch=master&job=Configuration%3A%20Release&pr=false

# Issues:
Infinite loading for mission "You shall not give false testimony, except for profit"

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/3588036/xenia.zip)

# Screenshot(s):
![title](https://user-images.githubusercontent.com/10359432/64494216-81696a80-d28a-11e9-802b-c3403a30bef1.jpg)

# Labels:
[state-hang]

**Comment by Margen67** [comment] 2019-09-08 20:53
Duplicate of #108.

**Closed** 2019-09-08 20:53 UTC
Labels: issue-duplicate
