### ISSUE TITLE
Pro Evolution Soccer 2008

### ISSUE THREAD

**Issue by Gazthehero69** [xenia-project/game-compatibility#2212] opened 2024-07-29 09:19 UTC
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch. (not MLBS/AlexVS/Canary/pull requests, etc)
- [X] This issue isn't for help (tech support) with Xenia, or a game.
- [X] I've checked if this game doesn't already have a compatibility report.

### Xenia version

https://github.com/xenia-project/xenia/commit/.../

### Issues

Crashes once I press start

### Log

[xenia.zip](https://github.com/user-attachments/files/16410455/xenia.zip)

### Screenshots

![1722244710519731549790269869292](https://github.com/user-attachments/assets/4db8e9e5-3d2c-4d8c-a466-77b59e8c0744)

### Labels

Unknown

**Comment by Margen67** [comment] 2024-07-29 09:34
Useless duplicate of #2143

**Closed by Margen67** 2024-07-29 09:34 UTC
