### ISSUE TITLE
524C07D9 - Alarm für Cobra 11: Crash Time III

### ISSUE THREAD

**Issue by MrGTAmodsgerman** [xenia-project/game-compatibility#1096] opened 2018-10-20 09:18 UTC
[Marketplace](http://marketplace.xbox.com/de-DE/Product/Highway-Nights/66acd000-77fe-1000-9115-d802524c07d9)

Tested on (https://github.com/benvanik/xenia/commit/2fa7607547ce9222b012fd700ea8d24304bc5dec)

# Issues:
Nothing to continue at beginning of the game in the section of createing a new game save or loading a game save. 
The game seems to work but there is some button missing to finally come into the real gameplay

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/2497975/xenia.zip)

# Screenshot(s):
![](https://i.imgur.com/P2RynlU.png)
![](https://i.imgur.com/fwx8EAv.png)
![](https://i.imgur.com/6wLnKBA.png)
![](https://i.imgur.com/cp2X1U0.png)

# Labels:
The link for the list of labels doesn't work.

**Comment by Ulquiorr4-Cifer** [comment] 2018-10-20 11:19
> The link for the list of labels doesn't work. 

🤔

**Comment by Gliniak** [comment] 2020-09-28 18:23
Duplicate of #232

**Closed by Gliniak** 2020-09-28 18:23 UTC
Labels: state-menus, tech-engine-unreal
