### ISSUE TITLE
415608CB - Call of Duty: Modern Warfare 3

### ISSUE THREAD

**Issue by FranciscoCarlosJunior** [xenia-project/game-compatibility#1537] opened 2020-04-28 16:31 UTC
[Marketplace](https://marketplace.xbox.com/en-us/Product/Modern-Warfare-3/66acd000-77fe-1000-9115-d802415608cb)

Tested on https://github.com/xenia-project/xenia/commit/0f0ed0eb2141cbf4fee391067068c0d92f1574b4

# Issues:
Works Fine. Menu OK. Audio OK.

# Log:
Too big (60MB)

# Screenshot(s):
![2020_04_28_11_58_15_1364x736](https://user-images.githubusercontent.com/60429667/80512727-f12c8280-894b-11ea-93b2-911ca3b70951.jpg)
![2020_04_28_12_22_26_1364x768](https://user-images.githubusercontent.com/60429667/80512741-f689cd00-894b-11ea-991c-a2c6c6cbe674.jpg)

# Labels:
state-gameplay
tech-engine-iw

**Comment by ernestott13** [comment] 2020-04-28 19:37
Donde puedo descargar este juego??

**Comment by Margen67** [comment] 2020-04-28 19:49
@ernestott13 https://github.com/xenia-project/game-compatibility#what-not-to-post

**Comment by Margen67** [comment] 2020-05-15 14:39
Duplicate of #386

**Closed by Margen67** 2020-05-15 14:39 UTC
Labels: issue-duplicate
