### ISSUE TITLE
445007F4 - お姉チャンバラZ ～カグラ～

### ISSUE THREAD

**Issue by Etokapa** [xenia-project/game-compatibility#1283] opened 2019-07-06 16:50 UTC
Game Title:
お姉チャンバラZ ～カグラ～
OneeChanbara Z ~ Kagura ~
Onechambara Z Kagura
Onechanbara Z Kagura

[Marketplace](https://marketplace.xbox.com/ja-JP/Product/%E3%81%8A%E5%A7%89%E3%83%81%E3%83%A3%E3%83%B3%E3%83%90%E3%83%A9Z-%E3%82%AB%E3%82%B0%E3%83%A9/66acd000-77fe-1000-9115-d802445007f4)

Tested on https://github.com/xenia-project/xenia/commit/f7ea93148a9ec9ff0ad9edac8c01854bd6153a10

Briefly played first part of the game. 60FPS.

# Issues:
• Audio is delayed.
• Audio is either too loud or too quiet.
• It's too dark to play.

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/3364860/xenia.zip)

# Screenshot(s):
![o (1)](https://user-images.githubusercontent.com/31154606/60759018-08c50400-9fe4-11e9-8cc1-ced50449b402.png)
![o (2)](https://user-images.githubusercontent.com/31154606/60759019-08c50400-9fe4-11e9-8331-405d5d98100a.png)
![o (3)](https://user-images.githubusercontent.com/31154606/60759020-08c50400-9fe4-11e9-9663-768b8ddde791.png)
![o (4)](https://user-images.githubusercontent.com/31154606/60759021-08c50400-9fe4-11e9-95f8-811997dfea62.png)
![o (5)](https://user-images.githubusercontent.com/31154606/60759022-08c50400-9fe4-11e9-99dc-643785a1c995.png)
![o (6)](https://user-images.githubusercontent.com/31154606/60759023-08c50400-9fe4-11e9-8e1a-6b7e9517a957.png)
![o (7)](https://user-images.githubusercontent.com/31154606/60759024-08c50400-9fe4-11e9-92b5-0945a5b019ec.png)

# Labels:
state-gameplay | apu-slow | gpu-shader-error

**Comment by illusion98** [comment] 2019-07-07 16:32
Duplicate of https://github.com/xenia-project/game-compatibility/issues/984

**Closed by illusion98** 2019-07-07 16:32 UTC
Labels: apu-slow, gpu-missing-drawing, gpu-shader-errors, state-gameplay
