### ISSUE TITLE
Guitar Hero Metallica - Menus

### ISSUE THREAD

**Issue by brenoyure** [xenia-project/game-compatibility#374] opened 2016-01-02 17:44 UTC
Guitar Hero Metallica only "works" in menus, when try to enter in game, it crashes.
I used a Guitar Controller (Xinput).

https://www.youtube.com/watch?v=mYWIE2qObI4

PCSpecs:
CPU: Intel Core i7 3770 @ 3,9 GHz
VGA:: EVGA Geforce GTX 660 Ti FTW 2GB GDDR5
RAM: Dual Channel 12GB (8GB + 4GB) Kingston DDR3 Memory HyperX Fury (Black) 1600MHz.
Placa Mãe Gigabyte GA B75M-D3H (rev 1.2)
SO: Windows 10 Pro x64 (1511 - build 10586)

Softwares used:
Xenia Emulator
Guitar Hero Metallica
Fraps
MSI Afterburner + Rivatuner Statics Server

**Comment by Nezarn** [comment] 2016-01-02 20:18
why did you open another issue for this game? duplicate of https://github.com/xenia-project/game-compatibility/issues/185

**Closed** 2016-01-02 20:33 UTC
