### ISSUE TITLE
Deadpool Cutscene Audio Does Not Work 

### ISSUE THREAD

**Issue by mrmysterious007** [xenia-project/game-compatibility#2213] opened 2024-08-04 04:12 UTC
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch. (not MLBS/AlexVS/Canary/pull requests, etc)
- [X] This issue isn't for help (tech support) with Xenia, or a game.
- [X] I've checked if this game doesn't already have a compatibility report.

### Xenia version

https://github.com/xenia-project/xenia/commit/.../

### Issues

deadpool cutscene audio is muted but nothing else.

### Log

[xenia.log](https://github.com/user-attachments/files/16486266/xenia.log)

### Screenshots

![Screenshot 2024-08-04 001050](https://github.com/user-attachments/assets/7337b400-852d-4b56-884f-eaf8d1808611)
![Screenshot 2024-08-04 001058](https://github.com/user-attachments/assets/639afe7a-d491-4201-a87a-0a289583d74d)

### Labels

apu-silent

**Comment by Margen67** [comment] 2024-08-04 09:06
Duplicate of #626

**Closed by Margen67** 2024-08-04 09:06 UTC
