### ISSUE TITLE
58411498 - Goat Simulator

### ISSUE THREAD

**Issue by soulfit15** [xenia-project/game-compatibility#1740] opened 2021-04-24 08:35 UTC
58411498 - Goat Simulator 

[Marketplace](https://marketplace.xbox.com/en-US/Product/Goat-Simulator/66acd000-77fe-1000-9115-d80258411498)

Tested on https://github.com/xenia-project/xenia/commit/6a2570595de232461c613a22d37fcf1e2c918172
# Issues:
the game most of the time is playable with good fps but there are times 
 the fps dips a good chunk to about 19 fps on my PC(FX-6350 + GTX 960 2GB) when loading grass/trees an in the second screenshot 

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/6369209/xenia.zip)
(warning! around 200mb logfile)

# Screenshot(s):
![Screenshot 2021-04-24 095034](https://user-images.githubusercontent.com/83112898/115952365-c84eb700-a4e5-11eb-86a3-286bb85d23cc.jpg)
![SharedScreenshot](https://user-images.githubusercontent.com/83112898/115952370-cb49a780-a4e5-11eb-960f-9484e854ade8.jpg)

# Labels:
state-playable | tech-engine-unreal

**Comment by ZolaKluke** [comment] 2021-04-24 09:01
Duplicate of https://github.com/xenia-project/game-compatibility/issues/406

**Closed** 2021-04-24 09:02 UTC
Labels: state-playable, tech-engine-unreal
