### ISSUE TITLE
Doesn't even run. Black screen for Hexic

### ISSUE THREAD

**Issue by OokamiWolfCanine** [xenia-project/game-compatibility#1107] opened 2018-11-13 03:21 UTC
[Marketplace](http://marketplace.xbox.com/...)

Tested on (xenia commit link)

# Issues:
(state of the game)

# Log:
Compress your logfile into a compressed folder named xenia.zip and then click and drag it here (replacing this text).

# Screenshot(s):
![](Screenshot URL)

# Labels:
(recommended labels)

**Comment by Margen67** [comment] 2018-11-13 04:40
Please fill out the template. It's there for a reason. Also, this is a duplicate of #141

**Closed** 2018-11-13 07:31 UTC
