### ISSUE TITLE
545408B2 - WWE 2k14

### ISSUE THREAD

**Issue by SteveChomu** [xenia-project/game-compatibility#1500] opened 2020-03-02 10:09 UTC
[Marketplace](https://marketplace.xbox.com/en-us/Product/WWE-2K14/66acd000-77fe-1000-9115-d802545408b2)

Tested on https://github.com/xenia-project/xenia/commit/714ad696745624c2b2791ea4b69b33ae73fe5d92

# Issues:
Infinite loading screen on release.

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/4274706/xenia.zip)

# Screenshot(s):
![Annotation 2020-03-02 153236](https://user-images.githubusercontent.com/61686894/75666211-6d338280-5c9b-11ea-8985-15eb5d4cd491.png)

# Labels:
(state-title)

**Comment by ZolaKluke** [comment] 2020-03-02 10:17
Can you please close this issue, it's a duplicate of https://github.com/xenia-project/game-compatibility/issues/1361

**Comment by ZolaKluke** [comment] 2020-03-02 10:19
Can you please delete this, it's a duplicate of https://github.com/xenia-project/game-compatibility/issues/1500

**Comment by SteveChomu** [comment] 2020-03-02 10:20
Ok i will

**Closed** 2020-03-02 10:20 UTC
