### ISSUE TITLE
53450812 - Sonic Unleashed

### ISSUE THREAD

**Issue by gottagofaster236** [xenia-project/game-compatibility#1462] opened 2019-11-07 16:09 UTC
[Marketplace](http://marketplace.xbox.com/...)

Tested on https://github.com/xenia-project/xenia/commit/d4a5a57867b3bc8e0337b4981884e8983b4af14c

# Issues:
In all of the levels Xenia reaches gameplay, but there are crashes. Some of them occur randomly, and some are consistent (for example, the crash on the very first level of the game, the log of which is attached).

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/3820458/xenia.zip)

# Screenshot(s):
![screenshot](https://user-images.githubusercontent.com/55288842/68405145-a39b3e00-0190-11ea-9808-7d5c4196993f.png)

# Labels:
(recommended labels)

state-gameplay
gpu-corrupt-drawing

**Comment by Margen67** [comment] 2019-11-07 16:11
Duplicate of #300.

**Closed by Margen67** 2019-11-07 16:11 UTC
Labels: issue-duplicate
