### ISSUE TITLE
58410975 - 3 on 3 NHL Arcade

### ISSUE THREAD

**Issue by badmuchachob** [xenia-project/game-compatibility#1695] opened 2021-01-21 00:23 UTC
[Marketplace](https://marketplace.xbox.com/en-US/Product/3-on-3-NHL-Arcade/66acd000-77fe-1000-9115-d80258410975)

Tested on https://github.com/xenia-project/xenia/commit/9a74df491ffd0189ddd26bc2030e0eae6a775f4e

# Issues:
Almost all of the text in the game loads incorrectly, ranging from missing letters to completely invisible. This means you cannot see the names of the players you select when starting a match, and the score and time during a match is missing. 

The kneepads and gloves on the players are black instead of white.

Despite this, the game plays and controls perfectly fine so playing full matches is possible.

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/5845988/xenia.zip)

# Screenshot(s):
![](https://cdn.discordapp.com/attachments/519297721186648064/801607033115115550/unknown.png)
![](https://cdn.discordapp.com/attachments/519297721186648064/801607148542361630/unknown.png)
![](https://cdn.discordapp.com/attachments/519297721186648064/801607253341634580/unknown.png)
![](https://media.discordapp.net/attachments/519297721186648064/801606812964880434/unknown.png?width=1122&height=676)

# Labels:
marketplace-nodownload, state-gameplay

**Comment by Prism019** [comment] 2021-01-21 01:39
Duplicate of #772

**Closed by Prism019** 2021-01-21 01:39 UTC
