### ISSUE TITLE
545407e5 - CIVILIZATION REVOLUTION

### ISSUE THREAD

**Issue by Mezahhh** [xenia-project/game-compatibility#1571] opened 2020-05-27 20:23 UTC
Xbox 360 Marketplace links only.
https://www.microsoft.com/fr-fr/p/civilization-revolution/9wzdncrfhxht?activetab=pivot:overviewtab

#Tested: 
on the last version

# Issues:
The game wont start

# Log:
There is no log

# Screenshot(s):
![]http://prntscr.com/sozfgh
# Labels:
(recommended labels)
state-nothing

**Comment by Mezahhh** [comment] 2020-05-27 20:23
#1023

**Comment by Margen67** [comment] 2020-05-28 08:40
Duplicate of #1023

**Closed by Margen67** 2020-05-28 08:40 UTC
Labels: issue-duplicate, issue-invalid
