### ISSUE TITLE
565507E4 - Crash Of The Titans

### ISSUE THREAD

**Issue by NvidiaGamerXIII** [xenia-project/game-compatibility#1113] opened 2018-12-03 00:12 UTC
[Marketplace](https://marketplace.xbox.com/en-US/Product/Crash-Of-The-Titans/66acd000-77fe-1000-9115-d802565507e4)

Tested on https://ci.appveyor.com/project/benvanik/xenia/builds/20655950

# Issues:
Like before, you need to use at least 4x CPU speed to get past the loading screens and most of the audio is still missing. It now goes ingame, but the game cannot be saved. There's a few graphical glitches, such as the dark pixels during the cutscenes, the outlined boxes around the health bars, and some particles being discolored and garbled.

# Log:
[crashofthetitans.zip](https://github.com/xenia-project/game-compatibility/files/2637595/crashofthetitans.zip)

# Video:
https://www.youtube.com/watch?v=Eg1TtWmPTFY

# Labels:
state-gameplay

**Comment by illusion98** [comment] 2019-07-06 14:30
duplicate of https://github.com/xenia-project/game-compatibility/issues/521

**Closed by illusion98** 2019-07-06 14:30 UTC
Labels: state-gameplay
