### ISSUE TITLE
584111F7 - Minecraft Xbox 360 Edition

### ISSUE THREAD

**Issue by angermanaged** [xenia-project/game-compatibility#1861] opened 2021-12-11 10:00 UTC
[Marketplace](http://marketplace.xbox.com/...)

Tested on https://github.com/xenia-project/xenia/commit/211cc99f4

# Issues:
hangs on "loading spawn area" for about 1-7 minutes while initializing server when loading a save file or creating a new world, then takes me back to the main menu with an error message saying "connection to XBOX LIVE was lost. Exiting to the main menu". The game is unplayable after updating to this build of xenia.

# Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/7696741/xenia.zip)

# Screenshot(s):
![Xenia (master@211cc99f4 on Nov 12 2021) _  584111F7 v1 0  Minecraft _Direct3D 12 - RTV_DSV_ 12_11_2021 1_31_28 AM](https://user-images.githubusercontent.com/81065551/145671968-32b6c9ce-8da7-4a18-98f5-ab4c4266aae6.png)
![Xenia (master@211cc99f4 on Nov 12 2021) _  584111F7 v1 0  Minecraft _Direct3D 12 - RTV_DSV_ 12_11_2021 1_31_39 AM](https://user-images.githubusercontent.com/81065551/145672015-197fde54-058e-4f94-b3e2-d7dc4d0d0dc4.png)

# Labels:
https://github.com/xenia-project/game-compatibility/labels/state-menus

**Comment by Margen67** [comment] 2021-12-11 10:01
Duplicate of #29

**Comment by angermanaged** [comment] 2021-12-11 10:03
> Duplicate of #29

i noticed that but seeing as this hasnt been a problem (for me at least) since that build i thought it would be important to post it. so could this be called a regression?

**Comment by angermanaged** [comment] 2021-12-11 10:09
> Duplicate of #29

and this is off topic, but since im new to reporting things, if i want to report issues for this game in the future would i take it to #29?

**Comment by Triang3l** [comment] 2021-12-11 10:10
> > Duplicate of #29
> 
> and this is off topic, but since im new to reporting things, if i want to report issues for this game in the future would i take it to #29?

Yes, I've moved your report to the original tracker entry for the game.

**Closed by Triang3l** 2021-12-11 10:10 UTC
