### ISSUE TITLE
53450812 - SONIC UNLEASHED

### ISSUE THREAD

**Issue by eletronik486100** [xenia-project/game-compatibility#1487] opened 2020-01-13 21:43 UTC
[Marketplace](https://marketplace.xbox.com/en-US/Product/SONIC-UNLEASHED/66acd000-77fe-1000-9115-d80253450812)

Tested on: https://github.com/xenia-project/xenia/commit/f748e5af49062fd78d098acdaf045183f29faf36

Issues:
After some playing time, a blackscreen appears and the game crashes (the message crash is: the guest has crashed) and this happens in almost every stage, however, the game works great on my gt 1030.

Screenshots:
![unleashedcrash](https://user-images.githubusercontent.com/59848410/72294285-9a649c80-362b-11ea-80f9-5da1864650f0.png)

Logfile:
https://drive.google.com/file/d/1mFPQWynHONjqO25flYINcSWhGAjbx-N7/view?usp=sharing

Labels:
gpu-missing-drawing
gpu-corrupt-drawing
state-gameplay

**Comment by eletronik486100** [comment] 2020-01-13 21:46
!> 00000028 ResolvePath(ShaderDumpxe:\CompareBackEnds) failed - device not found
this is the issue

**Comment by illusion98** [comment] 2020-01-13 21:48
Duplicate of #792

**Closed by illusion98** 2020-01-13 21:48 UTC
