### ISSUE TITLE
454108E6 - Skate 3 

### ISSUE THREAD

**Issue by EdSnowden123** [xenia-project/game-compatibility#591] opened 2016-08-18 00:23 UTC
http://marketplace.xbox.com/en-US/Product/Skate-3/66acd000-77fe-1000-9115-d802454108e6

Testing on 8/18/16. 

# Issues:

The game starts and I have gotten past the start screen, but then the game says I have chosen removable storage and tells me not to remove it, I press a to continue and get this error message: `Unhandled exception at 0x00000000A000EF8A in xenia.exe: 0xC0000005: Access violation writing location 0x0000000100000018.`

No issue before the crash, everything looks fine.

# Log:
https://gist.github.com/EdSnowden123/5616f2cb9856daf04687ec4df1b4cce7

# Screenshot(s):
![image](https://cloud.githubusercontent.com/assets/16494867/17757856/3f7fa9d6-64e2-11e6-9c33-7817c6f82974.png)

# Labels:
(recommended labels) state-crash 

Sorry if I have formatted this wrong or something, this is all my sleep deprived brain can handle

**Comment by MarioSonic2987** [comment] 2016-08-18 04:50
Duplicate of #201.

**Comment by Razzile** [comment] 2016-08-18 04:54
so it is

**Closed by Razzile** 2016-08-18 04:54 UTC
Labels: state-crash
