### ISSUE TITLE
5841125E - Joyride Turbo

### ISSUE THREAD

**Issue by Vaporcide** [xenia-project/game-compatibility#2232] opened 2024-10-21 13:59 UTC
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch. (not MLBS/AlexVS/Canary/pull requests, etc)
- [X] This issue isn't for help (tech support) with Xenia, or a game.
- [X] I've checked if this game doesn't already have a compatibility report.

### Xbox 360 Marketplace link

https://www.xbox.com/en-US/games/store/joy-ride-turbo/C1ZWH2BZ9TSF

### Xenia version

https://github.com/xenia-project/xenia/commit/3d30b2eec3ab1f83140b09745bee881fb5d5dde2/

### Issues

Lots of graphical glitches, audio seems to be fine but the game looks like it has a PS1 filter on, avatars also didn't work since avatars aren't currently supported. Other than that it played fine.

### Log

[xenia.log](https://github.com/user-attachments/files/17461956/xenia.log)

### Screenshots

![Screenshot 2024-10-21 085040](https://github.com/user-attachments/assets/0a1bf950-45ed-4603-9945-38cf21665490)
![Screenshot 2024-10-21 085056](https://github.com/user-attachments/assets/1f5ba893-4982-4459-9188-950162600181)
![Screenshot 2024-10-21 085113](https://github.com/user-attachments/assets/161f0ae8-40cd-4d5d-b96f-319ee096ca17)
![Screenshot 2024-10-21 085117](https://github.com/user-attachments/assets/0b4d6212-6b93-49f7-aa48-4cc253257596)
![Screenshot 2024-10-21 085206](https://github.com/user-attachments/assets/76a8d92e-4299-44f4-9e6e-5631543d2d8b)

### Labels

gpu-drawing-corrupt, state-gameplay, tech-avatar-required

**Comment by Margen67** [comment] 2024-10-21 14:07
Duplicate of #1424

**Closed by Margen67** 2024-10-21 14:07 UTC
